Algoritmo "semnome"
// 
//  
// Descrição   : Programa que detecta fatoriais
// Autor(a)    : Danilo Henrique de Oliveira Garcia
// Data atual  : 17/09/2022
Var
// Seção de Declarações das variáveis 
i, fb, num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i:=1
fb:=1
escreva("digite um numero: ")
leia(num)
para i de 1 ate num passo 1 faca
    fb:=fb*i
fimpara
escreva(fb)


Fimalgoritmo